"use client";

import { useMemo, useState } from "react";

type Rule = {
  id: number;
  userAgent: string;
  disallow: string;
  allow: string;
};

export default function RobotsTxtGenerator() {
  const [userAgent, setUserAgent] = useState("*");
  const [disallow, setDisallow] = useState("");
  const [allow, setAllow] = useState("/");
  const [sitemap, setSitemap] = useState("");
  const [crawlDelay, setCrawlDelay] = useState("");
  const [includeSitemap, setIncludeSitemap] = useState(true);
  const [includeCrawlDelay, setIncludeCrawlDelay] =
    useState(false);

  const [rules, setRules] = useState<Rule[]>([]);

  const generatedRobots = useMemo(() => {
    const lines: string[] = [
      "# Robots.txt generated by ToolVoraa",
      "",
      `User-agent: ${userAgent || "*"}`,
    ];

    if (allow.trim()) {
      lines.push(`Allow: ${allow.trim()}`);
    }

    if (disallow.trim()) {
      const paths = disallow
        .split("\n")
        .map((item) => item.trim())
        .filter(Boolean);

      paths.forEach((path) => {
        lines.push(`Disallow: ${path}`);
      });
    }

    if (includeCrawlDelay && crawlDelay.trim()) {
      lines.push(`Crawl-delay: ${crawlDelay.trim()}`);
    }

    rules.forEach((rule) => {
      lines.push(
        "",
        `User-agent: ${rule.userAgent || "*"}`,
      );

      if (rule.allow.trim()) {
        lines.push(`Allow: ${rule.allow.trim()}`);
      }

      if (rule.disallow.trim()) {
        rule.disallow
          .split("\n")
          .map((item) => item.trim())
          .filter(Boolean)
          .forEach((path) => {
            lines.push(`Disallow: ${path}`);
          });
      }
    });

    if (includeSitemap && sitemap.trim()) {
      lines.push("", `Sitemap: ${sitemap.trim()}`);
    }

    return lines.join("\n");
  }, [
    userAgent,
    disallow,
    allow,
    sitemap,
    crawlDelay,
    includeSitemap,
    includeCrawlDelay,
    rules,
  ]);

  function addRule() {
    setRules([
      ...rules,
      {
        id: Date.now(),
        userAgent: "Googlebot",
        disallow: "",
        allow: "/",
      },
    ]);
  }

  function updateRule(
    id: number,
    field: keyof Rule,
    value: string
  ) {
    setRules(
      rules.map((rule) =>
        rule.id === id
          ? {
              ...rule,
              [field]: value,
            }
          : rule
      )
    );
  }

  function removeRule(id: number) {
    setRules(
      rules.filter((rule) => rule.id !== id)
    );
  }

  async function copyRobots() {
    try {
      await navigator.clipboard.writeText(
        generatedRobots
      );

      alert("robots.txt copied successfully!");
    } catch {
      alert("Unable to copy robots.txt.");
    }
  }

  function downloadRobots() {
    const blob = new Blob(
      [generatedRobots],
      {
        type: "text/plain;charset=utf-8",
      }
    );

    const downloadUrl =
      URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = downloadUrl;
    link.download = "robots.txt";

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(downloadUrl);
  }

  function clearAll() {
    setUserAgent("*");
    setDisallow("");
    setAllow("/");
    setSitemap("");
    setCrawlDelay("");
    setIncludeSitemap(true);
    setIncludeCrawlDelay(false);
    setRules([]);
  }

  function generateExample() {
    setUserAgent("*");
    setAllow("/");
    setDisallow(
      "/admin/\n/private/\n/checkout/\n/cart/"
    );
    setSitemap(
      "https://example.com/sitemap.xml"
    );
    setIncludeSitemap(true);
    setIncludeCrawlDelay(false);
  }

  return (
    <main className="page">
      <div className="container">

        <header className="header">
          <div className="badge">
            SEO TOOL
          </div>

          <h1>Robots.txt Generator</h1>

          <p>
            Create a robots.txt file to control how
            search engine crawlers access your website.
          </p>
        </header>

        <section className="grid">

          {/* LEFT PANEL */}

          <div className="card">

            <div className="cardHeader">
              <div>
                <h2>
                  Robots.txt Settings
                </h2>

                <p>
                  Configure crawler access rules.
                </p>
              </div>

              <button
                type="button"
                className="clearButton"
                onClick={clearAll}
              >
                Clear
              </button>
            </div>

            <label>
              User-agent
            </label>

            <select
              value={userAgent}
              onChange={(e) =>
                setUserAgent(e.target.value)
              }
            >
              <option value="*">
                All Search Engines (*)
              </option>

              <option value="Googlebot">
                Googlebot
              </option>

              <option value="Bingbot">
                Bingbot
              </option>

              <option value="Googlebot-Image">
                Google Images
              </option>

              <option value="GPTBot">
                GPTBot
              </option>

              <option value="Amazonbot">
                Amazonbot
              </option>
            </select>

            <label>
              Allow Path
            </label>

            <input
              type="text"
              value={allow}
              onChange={(e) =>
                setAllow(e.target.value)
              }
              placeholder="/"
            />

            <div className="help">
              Use / to allow the entire website.
            </div>

            <label>
              Disallow Paths
            </label>

            <textarea
              value={disallow}
              onChange={(e) =>
                setDisallow(e.target.value)
              }
              placeholder={`/admin/
/private/
/checkout/`}
              rows={7}
            />

            <div className="help">
              Enter one path per line.
            </div>

            <div className="option">
              <label className="checkboxLabel">
                <input
                  type="checkbox"
                  checked={includeCrawlDelay}
                  onChange={(e) =>
                    setIncludeCrawlDelay(
                      e.target.checked
                    )
                  }
                />

                <span>
                  Add Crawl-delay
                </span>
              </label>
            </div>

            {includeCrawlDelay && (
              <>
                <label>
                  Crawl Delay
                </label>

                <input
                  type="number"
                  min="0"
                  value={crawlDelay}
                  onChange={(e) =>
                    setCrawlDelay(
                      e.target.value
                    )
                  }
                  placeholder="10"
                />

                <div className="help">
                  Delay value in seconds.
                </div>
              </>
            )}

            <div className="option">
              <label className="checkboxLabel">
                <input
                  type="checkbox"
                  checked={includeSitemap}
                  onChange={(e) =>
                    setIncludeSitemap(
                      e.target.checked
                    )
                  }
                />

                <span>
                  Include Sitemap
                </span>
              </label>
            </div>

            {includeSitemap && (
              <>
                <label>
                  Sitemap URL
                </label>

                <input
                  type="url"
                  value={sitemap}
                  onChange={(e) =>
                    setSitemap(
                      e.target.value
                    )
                  }
                  placeholder="https://example.com/sitemap.xml"
                />
              </>
            )}

            <button
              type="button"
              className="exampleButton"
              onClick={generateExample}
            >
              Load Example
            </button>

            {/* EXTRA RULES */}

            <div className="advancedHeader">
              <div>
                <h3>
                  Additional Bot Rules
                </h3>

                <p>
                  Add rules for specific crawlers.
                </p>
              </div>

              <button
                type="button"
                className="addButton"
                onClick={addRule}
              >
                + Add Rule
              </button>
            </div>

            {rules.map((rule, index) => (
              <div
                className="ruleBox"
                key={rule.id}
              >
                <div className="ruleHeader">
                  <strong>
                    Rule {index + 1}
                  </strong>

                  <button
                    type="button"
                    className="removeButton"
                    onClick={() =>
                      removeRule(rule.id)
                    }
                  >
                    Remove
                  </button>
                </div>

                <label>
                  User-agent
                </label>

                <input
                  type="text"
                  value={rule.userAgent}
                  onChange={(e) =>
                    updateRule(
                      rule.id,
                      "userAgent",
                      e.target.value
                    )
                  }
                  placeholder="Googlebot"
                />

                <label>
                  Allow
                </label>

                <input
                  type="text"
                  value={rule.allow}
                  onChange={(e) =>
                    updateRule(
                      rule.id,
                      "allow",
                      e.target.value
                    )
                  }
                  placeholder="/"
                />

                <label>
                  Disallow
                </label>

                <textarea
                  value={rule.disallow}
                  onChange={(e) =>
                    updateRule(
                      rule.id,
                      "disallow",
                      e.target.value
                    )
                  }
                  placeholder="/private/"
                  rows={3}
                />
              </div>
            ))}

          </div>

          {/* RIGHT PANEL */}

          <div className="card">

            <div className="cardHeader">
              <div>
                <h2>
                  Generated robots.txt
                </h2>

                <p>
                  Your robots.txt file is generated live.
                </p>
              </div>

              <div className="actions">

                <button
                  type="button"
                  className="secondaryButton"
                  onClick={copyRobots}
                >
                  Copy
                </button>

                <button
                  type="button"
                  className="primaryButton"
                  onClick={downloadRobots}
                >
                  Download
                </button>

              </div>
            </div>

            <div className="codeBox">
              <pre>
                {generatedRobots}
              </pre>
            </div>

            <div className="fileInfo">

              <div className="infoIcon">
                TXT
              </div>

              <div>
                <strong>
                  robots.txt
                </strong>

                <p>
                  Save this file in the root directory
                  of your website.
                </p>
              </div>

            </div>

            <div className="howTo">

              <h3>
                How to use robots.txt
              </h3>

              <ol>
                <li>
                  Configure your crawler rules.
                </li>

                <li>
                  Click Download.
                </li>

                <li>
                  Upload the file to your website root.
                </li>

                <li>
                  The file should normally be available at:
                </li>
              </ol>

              <div className="urlExample">
                https://example.com/robots.txt
              </div>

            </div>

            <div className="tips">

              <h3>
                SEO Tips
              </h3>

              <ul>
                <li>
                  Do not accidentally block important
                  pages or resources.
                </li>

                <li>
                  Keep your sitemap URL accurate.
                </li>

                <li>
                  Use specific crawler rules only when
                  you have a clear reason.
                </li>

                <li>
                  Check your robots.txt after publishing.
                </li>

                <li>
                  Remember that robots.txt is a crawler
                  instruction, not an access-control system.
                </li>
              </ul>

            </div>

          </div>

        </section>

      </div>

      <style>{`
        * {
          box-sizing: border-box;
        }

        .page {
          min-height: 100vh;
          background: #f5f7fb;
          color: #172033;
          padding: 40px 20px 70px;
        }

        .container {
          max-width: 1200px;
          margin: 0 auto;
        }

        .header {
          text-align: center;
          margin-bottom: 32px;
        }

        .badge {
          display: inline-block;
          padding: 7px 14px;
          border-radius: 999px;
          background: #e8efff;
          color: #3158c7;
          font-size: 12px;
          font-weight: 700;
          letter-spacing: 1px;
          margin-bottom: 12px;
        }

        h1 {
          margin: 0;
          font-size: 38px;
          line-height: 1.15;
          font-weight: 800;
        }

        .header p {
          max-width: 720px;
          margin: 12px auto 0;
          color: #667085;
          font-size: 16px;
          line-height: 1.6;
        }

        .grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 24px;
          align-items: start;
        }

        .card {
          background: #ffffff;
          border: 1px solid #e5e7eb;
          border-radius: 18px;
          padding: 24px;
          box-shadow:
            0 8px 30px rgba(15, 23, 42, 0.06);
        }

        .cardHeader {
          display: flex;
          align-items: flex-start;
          justify-content: space-between;
          gap: 16px;
          margin-bottom: 22px;
        }

        .cardHeader h2 {
          margin: 0;
          font-size: 20px;
          font-weight: 750;
        }

        .cardHeader p {
          margin: 5px 0 0;
          color: #667085;
          font-size: 13px;
        }

        label {
          display: block;
          margin: 17px 0 8px;
          font-size: 14px;
          font-weight: 650;
          color: #344054;
        }

        input,
        textarea,
        select {
          width: 100%;
          border: 1px solid #d0d5dd;
          border-radius: 10px;
          padding: 12px 13px;
          font-size: 14px;
          outline: none;
          background: #ffffff;
          color: #101828;
          transition:
            border 0.2s,
            box-shadow 0.2s;
        }

        input:focus,
        textarea:focus,
        select:focus {
          border-color: #5b7cfa;
          box-shadow:
            0 0 0 3px rgba(91, 124, 250, 0.12);
        }

        textarea {
          resize: vertical;
        }

        .help {
          margin-top: 6px;
          color: #667085;
          font-size: 12px;
          line-height: 1.5;
        }

        .clearButton,
        .secondaryButton,
        .primaryButton,
        .exampleButton,
        .addButton,
        .removeButton {
          border: none;
          border-radius: 9px;
          padding: 10px 14px;
          cursor: pointer;
          font-size: 13px;
          font-weight: 650;
        }

        .clearButton {
          background: #f2f4f7;
          color: #475467;
        }

        .secondaryButton {
          background: #eef2ff;
          color: #3b5bdb;
        }

        .primaryButton {
          background: #3158c7;
          color: #ffffff;
        }

        .primaryButton:hover {
          background: #2548aa;
        }

        .actions {
          display: flex;
          gap: 8px;
          flex-wrap: wrap;
        }

        .checkboxLabel {
          display: flex;
          align-items: center;
          gap: 10px;
          margin: 0;
          cursor: pointer;
          font-size: 13px;
          font-weight: 600;
        }

        .checkboxLabel input {
          width: 17px;
          height: 17px;
          accent-color: #3158c7;
        }

        .option {
          margin-top: 18px;
          padding: 12px;
          border-radius: 10px;
          background: #f8fafc;
          border: 1px solid #e5e7eb;
        }

        .exampleButton {
          width: 100%;
          margin-top: 18px;
          background: #f2f4f7;
          color: #344054;
        }

        .exampleButton:hover {
          background: #e4e7ec;
        }

        .advancedHeader {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          margin-top: 28px;
          padding-top: 22px;
          border-top: 1px solid #e5e7eb;
        }

        .advancedHeader h3 {
          margin: 0;
          font-size: 16px;
        }

        .advancedHeader p {
          margin: 5px 0 0;
          color: #667085;
          font-size: 12px;
        }

        .addButton {
          background: #3158c7;
          color: #ffffff;
        }

        .ruleBox {
          margin-top: 15px;
          padding: 17px;
          border-radius: 12px;
          background: #f8fafc;
          border: 1px solid #e5e7eb;
        }

        .ruleHeader {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 10px;
        }

        .removeButton {
          background: #fff1f2;
          color: #be123c;
        }

        .codeBox {
          min-height: 430px;
          max-height: 620px;
          overflow: auto;
          background: #101828;
          border-radius: 12px;
          padding: 20px;
        }

        .codeBox pre {
          margin: 0;
          color: #e6edf3;
          font-family: Consolas, Monaco, monospace;
          font-size: 13px;
          line-height: 1.8;
          white-space: pre-wrap;
          word-break: break-word;
        }

        .fileInfo {
          display: flex;
          align-items: center;
          gap: 13px;
          margin-top: 20px;
          padding: 16px;
          border-radius: 12px;
          background: #f8fafc;
          border: 1px solid #e5e7eb;
        }

        .infoIcon {
          width: 44px;
          height: 44px;
          display: flex;
          align-items: center;
          justify-content: center;
          border-radius: 10px;
          background: #eef2ff;
          color: #3158c7;
          font-size: 11px;
          font-weight: 800;
        }

        .fileInfo strong {
          font-size: 14px;
        }

        .fileInfo p {
          margin: 4px 0 0;
          color: #667085;
          font-size: 12px;
        }

        .howTo,
        .tips {
          margin-top: 20px;
          padding: 17px;
          border-radius: 12px;
          background: #f8fafc;
          border: 1px solid #e5e7eb;
        }

        .howTo h3,
        .tips h3 {
          margin: 0 0 10px;
          font-size: 15px;
        }

        .howTo ol,
        .tips ul {
          margin: 0;
          padding-left: 20px;
          color: #667085;
          font-size: 12px;
          line-height: 1.9;
        }

        .urlExample {
          margin-top: 12px;
          padding: 11px;
          border-radius: 8px;
          background: #ffffff;
          border: 1px solid #e5e7eb;
          color: #3158c7;
          font-family: Consolas, Monaco, monospace;
          font-size: 12px;
          word-break: break-all;
        }

        @media (max-width: 900px) {
          .grid {
            grid-template-columns: 1fr;
          }

          h1 {
            font-size: 32px;
          }
        }

        @media (max-width: 560px) {
          .page {
            padding: 25px 12px 50px;
          }

          .card {
            padding: 18px;
            border-radius: 14px;
          }

          .cardHeader,
          .advancedHeader {
            flex-direction: column;
            align-items: flex-start;
          }

          .actions {
            width: 100%;
          }

          .secondaryButton,
          .primaryButton {
            flex: 1;
          }
        }
      `}</style>
    </main>
  );
}